version: '3.8'

#volumes:
#  redis-data:
#    null
services:
  app:
    image: mcr.microsoft.com/devcontainers/python:0-3.9

    # Security Opt and cap_add allow for C++ based debuggers to work. 
    # See `runArgs`: https://github.com/Microsoft/vscode-docs/blob/main/docs/remote/devcontainerjson-reference.md
    #     security_opt:
    #       - seccomp:unconfined
    #     cap_add:
    #       - SYS_PTRACE

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    #network_mode: service:redis
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  epics_pva:
    image: ghcr.io/bisegni/epics-base-docker-image:main
    volumes:
      - ../tests/epics-test.db:/db/softioc.db

  k2eg:
    image: ghcr.io/slaclab/k2eg/ubuntu:latest
    pull_policy: always
    entrypoint: k2eg
    depends_on: 
      - kafka
    command: [
      "--log-level=trace", 
      "--cmd-input-topic=cmd-in-topic", 
      "--sub-server-address=kafka:9092", 
      "--sub-group-id=eed-k2eg", 
      "--pub-server-address=kafka:9092",
      "--metric-enable=true",
      "--scheduler-check-delay-seconds=60",
      "--scheduler-thread-number=1",
      "--monitor-worker-cron-schedule=*/5 * * * * *",
      "--nc-monitor-expiration-timeout=1",
      "--nc-purge-queue-on-exp-timeout=true",
      "--nc-monitor-consumer-filterout-regex=.*k2eg.*"]
  
  kafka:
    image: docker.io/bitnami/kafka:3.6
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
volumes:
  kafka_data:
    driver: local